spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
    url: ${spring.data.mongodb.uri}

random-org:
  url: ${RANDOMORG_URL}

server:
  port: ${SERVER_PORT}
